version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: notepaper_db
    restart: always
    environment:
      POSTGRES_DB: uptime_monitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: redis:alpine
    container_name: notepaper_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

  mailpit:
    image: axllent/mailpit
    container_name: notepaper_mailpit
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data:
    driver: local
  cache:
    driver: local
